// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module y26_conv_top_partselect_8ns_128ns_7ns_8_1_1 (sel,din,dout);

parameter ADDRWIDTH = 7;
parameter DATAWIDTH = 128;
parameter DATA1WIDTH = 8;

input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
output [DATA1WIDTH-1:0] dout;

wire [DATA1WIDTH-1:0] dout_tmp;

assign dout_tmp = din[sel +: 8];

assign dout = dout_tmp;


endmodule
