// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="y26_conv_top_y26_conv_top,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.628000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=425,HLS_SYN_DSP=0,HLS_SYN_FF=78477,HLS_SYN_LUT=169573,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module y26_conv_top (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_act_AWVALID,
        m_axi_gmem_act_AWREADY,
        m_axi_gmem_act_AWADDR,
        m_axi_gmem_act_AWID,
        m_axi_gmem_act_AWLEN,
        m_axi_gmem_act_AWSIZE,
        m_axi_gmem_act_AWBURST,
        m_axi_gmem_act_AWLOCK,
        m_axi_gmem_act_AWCACHE,
        m_axi_gmem_act_AWPROT,
        m_axi_gmem_act_AWQOS,
        m_axi_gmem_act_AWREGION,
        m_axi_gmem_act_AWUSER,
        m_axi_gmem_act_WVALID,
        m_axi_gmem_act_WREADY,
        m_axi_gmem_act_WDATA,
        m_axi_gmem_act_WSTRB,
        m_axi_gmem_act_WLAST,
        m_axi_gmem_act_WID,
        m_axi_gmem_act_WUSER,
        m_axi_gmem_act_ARVALID,
        m_axi_gmem_act_ARREADY,
        m_axi_gmem_act_ARADDR,
        m_axi_gmem_act_ARID,
        m_axi_gmem_act_ARLEN,
        m_axi_gmem_act_ARSIZE,
        m_axi_gmem_act_ARBURST,
        m_axi_gmem_act_ARLOCK,
        m_axi_gmem_act_ARCACHE,
        m_axi_gmem_act_ARPROT,
        m_axi_gmem_act_ARQOS,
        m_axi_gmem_act_ARREGION,
        m_axi_gmem_act_ARUSER,
        m_axi_gmem_act_RVALID,
        m_axi_gmem_act_RREADY,
        m_axi_gmem_act_RDATA,
        m_axi_gmem_act_RLAST,
        m_axi_gmem_act_RID,
        m_axi_gmem_act_RUSER,
        m_axi_gmem_act_RRESP,
        m_axi_gmem_act_BVALID,
        m_axi_gmem_act_BREADY,
        m_axi_gmem_act_BRESP,
        m_axi_gmem_act_BID,
        m_axi_gmem_act_BUSER,
        m_axi_gmem_wt_AWVALID,
        m_axi_gmem_wt_AWREADY,
        m_axi_gmem_wt_AWADDR,
        m_axi_gmem_wt_AWID,
        m_axi_gmem_wt_AWLEN,
        m_axi_gmem_wt_AWSIZE,
        m_axi_gmem_wt_AWBURST,
        m_axi_gmem_wt_AWLOCK,
        m_axi_gmem_wt_AWCACHE,
        m_axi_gmem_wt_AWPROT,
        m_axi_gmem_wt_AWQOS,
        m_axi_gmem_wt_AWREGION,
        m_axi_gmem_wt_AWUSER,
        m_axi_gmem_wt_WVALID,
        m_axi_gmem_wt_WREADY,
        m_axi_gmem_wt_WDATA,
        m_axi_gmem_wt_WSTRB,
        m_axi_gmem_wt_WLAST,
        m_axi_gmem_wt_WID,
        m_axi_gmem_wt_WUSER,
        m_axi_gmem_wt_ARVALID,
        m_axi_gmem_wt_ARREADY,
        m_axi_gmem_wt_ARADDR,
        m_axi_gmem_wt_ARID,
        m_axi_gmem_wt_ARLEN,
        m_axi_gmem_wt_ARSIZE,
        m_axi_gmem_wt_ARBURST,
        m_axi_gmem_wt_ARLOCK,
        m_axi_gmem_wt_ARCACHE,
        m_axi_gmem_wt_ARPROT,
        m_axi_gmem_wt_ARQOS,
        m_axi_gmem_wt_ARREGION,
        m_axi_gmem_wt_ARUSER,
        m_axi_gmem_wt_RVALID,
        m_axi_gmem_wt_RREADY,
        m_axi_gmem_wt_RDATA,
        m_axi_gmem_wt_RLAST,
        m_axi_gmem_wt_RID,
        m_axi_gmem_wt_RUSER,
        m_axi_gmem_wt_RRESP,
        m_axi_gmem_wt_BVALID,
        m_axi_gmem_wt_BREADY,
        m_axi_gmem_wt_BRESP,
        m_axi_gmem_wt_BID,
        m_axi_gmem_wt_BUSER,
        m_axi_gmem_scale_AWVALID,
        m_axi_gmem_scale_AWREADY,
        m_axi_gmem_scale_AWADDR,
        m_axi_gmem_scale_AWID,
        m_axi_gmem_scale_AWLEN,
        m_axi_gmem_scale_AWSIZE,
        m_axi_gmem_scale_AWBURST,
        m_axi_gmem_scale_AWLOCK,
        m_axi_gmem_scale_AWCACHE,
        m_axi_gmem_scale_AWPROT,
        m_axi_gmem_scale_AWQOS,
        m_axi_gmem_scale_AWREGION,
        m_axi_gmem_scale_AWUSER,
        m_axi_gmem_scale_WVALID,
        m_axi_gmem_scale_WREADY,
        m_axi_gmem_scale_WDATA,
        m_axi_gmem_scale_WSTRB,
        m_axi_gmem_scale_WLAST,
        m_axi_gmem_scale_WID,
        m_axi_gmem_scale_WUSER,
        m_axi_gmem_scale_ARVALID,
        m_axi_gmem_scale_ARREADY,
        m_axi_gmem_scale_ARADDR,
        m_axi_gmem_scale_ARID,
        m_axi_gmem_scale_ARLEN,
        m_axi_gmem_scale_ARSIZE,
        m_axi_gmem_scale_ARBURST,
        m_axi_gmem_scale_ARLOCK,
        m_axi_gmem_scale_ARCACHE,
        m_axi_gmem_scale_ARPROT,
        m_axi_gmem_scale_ARQOS,
        m_axi_gmem_scale_ARREGION,
        m_axi_gmem_scale_ARUSER,
        m_axi_gmem_scale_RVALID,
        m_axi_gmem_scale_RREADY,
        m_axi_gmem_scale_RDATA,
        m_axi_gmem_scale_RLAST,
        m_axi_gmem_scale_RID,
        m_axi_gmem_scale_RUSER,
        m_axi_gmem_scale_RRESP,
        m_axi_gmem_scale_BVALID,
        m_axi_gmem_scale_BREADY,
        m_axi_gmem_scale_BRESP,
        m_axi_gmem_scale_BID,
        m_axi_gmem_scale_BUSER,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ACT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_ACT_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM_ACT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ACT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_ACT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_ACT_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_OUT_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_SCALE_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_SCALE_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_SCALE_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_SCALE_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_SCALE_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_SCALE_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_WT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_WT_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_WT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_WT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_WT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_ACT_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_OUT_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_GMEM_SCALE_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WT_WSTRB_WIDTH = (64 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_act_AWVALID;
input   m_axi_gmem_act_AWREADY;
output  [C_M_AXI_GMEM_ACT_ADDR_WIDTH - 1:0] m_axi_gmem_act_AWADDR;
output  [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_AWID;
output  [7:0] m_axi_gmem_act_AWLEN;
output  [2:0] m_axi_gmem_act_AWSIZE;
output  [1:0] m_axi_gmem_act_AWBURST;
output  [1:0] m_axi_gmem_act_AWLOCK;
output  [3:0] m_axi_gmem_act_AWCACHE;
output  [2:0] m_axi_gmem_act_AWPROT;
output  [3:0] m_axi_gmem_act_AWQOS;
output  [3:0] m_axi_gmem_act_AWREGION;
output  [C_M_AXI_GMEM_ACT_AWUSER_WIDTH - 1:0] m_axi_gmem_act_AWUSER;
output   m_axi_gmem_act_WVALID;
input   m_axi_gmem_act_WREADY;
output  [C_M_AXI_GMEM_ACT_DATA_WIDTH - 1:0] m_axi_gmem_act_WDATA;
output  [C_M_AXI_GMEM_ACT_WSTRB_WIDTH - 1:0] m_axi_gmem_act_WSTRB;
output   m_axi_gmem_act_WLAST;
output  [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_WID;
output  [C_M_AXI_GMEM_ACT_WUSER_WIDTH - 1:0] m_axi_gmem_act_WUSER;
output   m_axi_gmem_act_ARVALID;
input   m_axi_gmem_act_ARREADY;
output  [C_M_AXI_GMEM_ACT_ADDR_WIDTH - 1:0] m_axi_gmem_act_ARADDR;
output  [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_ARID;
output  [7:0] m_axi_gmem_act_ARLEN;
output  [2:0] m_axi_gmem_act_ARSIZE;
output  [1:0] m_axi_gmem_act_ARBURST;
output  [1:0] m_axi_gmem_act_ARLOCK;
output  [3:0] m_axi_gmem_act_ARCACHE;
output  [2:0] m_axi_gmem_act_ARPROT;
output  [3:0] m_axi_gmem_act_ARQOS;
output  [3:0] m_axi_gmem_act_ARREGION;
output  [C_M_AXI_GMEM_ACT_ARUSER_WIDTH - 1:0] m_axi_gmem_act_ARUSER;
input   m_axi_gmem_act_RVALID;
output   m_axi_gmem_act_RREADY;
input  [C_M_AXI_GMEM_ACT_DATA_WIDTH - 1:0] m_axi_gmem_act_RDATA;
input   m_axi_gmem_act_RLAST;
input  [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_RID;
input  [C_M_AXI_GMEM_ACT_RUSER_WIDTH - 1:0] m_axi_gmem_act_RUSER;
input  [1:0] m_axi_gmem_act_RRESP;
input   m_axi_gmem_act_BVALID;
output   m_axi_gmem_act_BREADY;
input  [1:0] m_axi_gmem_act_BRESP;
input  [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_BID;
input  [C_M_AXI_GMEM_ACT_BUSER_WIDTH - 1:0] m_axi_gmem_act_BUSER;
output   m_axi_gmem_wt_AWVALID;
input   m_axi_gmem_wt_AWREADY;
output  [C_M_AXI_GMEM_WT_ADDR_WIDTH - 1:0] m_axi_gmem_wt_AWADDR;
output  [C_M_AXI_GMEM_WT_ID_WIDTH - 1:0] m_axi_gmem_wt_AWID;
output  [7:0] m_axi_gmem_wt_AWLEN;
output  [2:0] m_axi_gmem_wt_AWSIZE;
output  [1:0] m_axi_gmem_wt_AWBURST;
output  [1:0] m_axi_gmem_wt_AWLOCK;
output  [3:0] m_axi_gmem_wt_AWCACHE;
output  [2:0] m_axi_gmem_wt_AWPROT;
output  [3:0] m_axi_gmem_wt_AWQOS;
output  [3:0] m_axi_gmem_wt_AWREGION;
output  [C_M_AXI_GMEM_WT_AWUSER_WIDTH - 1:0] m_axi_gmem_wt_AWUSER;
output   m_axi_gmem_wt_WVALID;
input   m_axi_gmem_wt_WREADY;
output  [C_M_AXI_GMEM_WT_DATA_WIDTH - 1:0] m_axi_gmem_wt_WDATA;
output  [C_M_AXI_GMEM_WT_WSTRB_WIDTH - 1:0] m_axi_gmem_wt_WSTRB;
output   m_axi_gmem_wt_WLAST;
output  [C_M_AXI_GMEM_WT_ID_WIDTH - 1:0] m_axi_gmem_wt_WID;
output  [C_M_AXI_GMEM_WT_WUSER_WIDTH - 1:0] m_axi_gmem_wt_WUSER;
output   m_axi_gmem_wt_ARVALID;
input   m_axi_gmem_wt_ARREADY;
output  [C_M_AXI_GMEM_WT_ADDR_WIDTH - 1:0] m_axi_gmem_wt_ARADDR;
output  [C_M_AXI_GMEM_WT_ID_WIDTH - 1:0] m_axi_gmem_wt_ARID;
output  [7:0] m_axi_gmem_wt_ARLEN;
output  [2:0] m_axi_gmem_wt_ARSIZE;
output  [1:0] m_axi_gmem_wt_ARBURST;
output  [1:0] m_axi_gmem_wt_ARLOCK;
output  [3:0] m_axi_gmem_wt_ARCACHE;
output  [2:0] m_axi_gmem_wt_ARPROT;
output  [3:0] m_axi_gmem_wt_ARQOS;
output  [3:0] m_axi_gmem_wt_ARREGION;
output  [C_M_AXI_GMEM_WT_ARUSER_WIDTH - 1:0] m_axi_gmem_wt_ARUSER;
input   m_axi_gmem_wt_RVALID;
output   m_axi_gmem_wt_RREADY;
input  [C_M_AXI_GMEM_WT_DATA_WIDTH - 1:0] m_axi_gmem_wt_RDATA;
input   m_axi_gmem_wt_RLAST;
input  [C_M_AXI_GMEM_WT_ID_WIDTH - 1:0] m_axi_gmem_wt_RID;
input  [C_M_AXI_GMEM_WT_RUSER_WIDTH - 1:0] m_axi_gmem_wt_RUSER;
input  [1:0] m_axi_gmem_wt_RRESP;
input   m_axi_gmem_wt_BVALID;
output   m_axi_gmem_wt_BREADY;
input  [1:0] m_axi_gmem_wt_BRESP;
input  [C_M_AXI_GMEM_WT_ID_WIDTH - 1:0] m_axi_gmem_wt_BID;
input  [C_M_AXI_GMEM_WT_BUSER_WIDTH - 1:0] m_axi_gmem_wt_BUSER;
output   m_axi_gmem_scale_AWVALID;
input   m_axi_gmem_scale_AWREADY;
output  [C_M_AXI_GMEM_SCALE_ADDR_WIDTH - 1:0] m_axi_gmem_scale_AWADDR;
output  [C_M_AXI_GMEM_SCALE_ID_WIDTH - 1:0] m_axi_gmem_scale_AWID;
output  [7:0] m_axi_gmem_scale_AWLEN;
output  [2:0] m_axi_gmem_scale_AWSIZE;
output  [1:0] m_axi_gmem_scale_AWBURST;
output  [1:0] m_axi_gmem_scale_AWLOCK;
output  [3:0] m_axi_gmem_scale_AWCACHE;
output  [2:0] m_axi_gmem_scale_AWPROT;
output  [3:0] m_axi_gmem_scale_AWQOS;
output  [3:0] m_axi_gmem_scale_AWREGION;
output  [C_M_AXI_GMEM_SCALE_AWUSER_WIDTH - 1:0] m_axi_gmem_scale_AWUSER;
output   m_axi_gmem_scale_WVALID;
input   m_axi_gmem_scale_WREADY;
output  [C_M_AXI_GMEM_SCALE_DATA_WIDTH - 1:0] m_axi_gmem_scale_WDATA;
output  [C_M_AXI_GMEM_SCALE_WSTRB_WIDTH - 1:0] m_axi_gmem_scale_WSTRB;
output   m_axi_gmem_scale_WLAST;
output  [C_M_AXI_GMEM_SCALE_ID_WIDTH - 1:0] m_axi_gmem_scale_WID;
output  [C_M_AXI_GMEM_SCALE_WUSER_WIDTH - 1:0] m_axi_gmem_scale_WUSER;
output   m_axi_gmem_scale_ARVALID;
input   m_axi_gmem_scale_ARREADY;
output  [C_M_AXI_GMEM_SCALE_ADDR_WIDTH - 1:0] m_axi_gmem_scale_ARADDR;
output  [C_M_AXI_GMEM_SCALE_ID_WIDTH - 1:0] m_axi_gmem_scale_ARID;
output  [7:0] m_axi_gmem_scale_ARLEN;
output  [2:0] m_axi_gmem_scale_ARSIZE;
output  [1:0] m_axi_gmem_scale_ARBURST;
output  [1:0] m_axi_gmem_scale_ARLOCK;
output  [3:0] m_axi_gmem_scale_ARCACHE;
output  [2:0] m_axi_gmem_scale_ARPROT;
output  [3:0] m_axi_gmem_scale_ARQOS;
output  [3:0] m_axi_gmem_scale_ARREGION;
output  [C_M_AXI_GMEM_SCALE_ARUSER_WIDTH - 1:0] m_axi_gmem_scale_ARUSER;
input   m_axi_gmem_scale_RVALID;
output   m_axi_gmem_scale_RREADY;
input  [C_M_AXI_GMEM_SCALE_DATA_WIDTH - 1:0] m_axi_gmem_scale_RDATA;
input   m_axi_gmem_scale_RLAST;
input  [C_M_AXI_GMEM_SCALE_ID_WIDTH - 1:0] m_axi_gmem_scale_RID;
input  [C_M_AXI_GMEM_SCALE_RUSER_WIDTH - 1:0] m_axi_gmem_scale_RUSER;
input  [1:0] m_axi_gmem_scale_RRESP;
input   m_axi_gmem_scale_BVALID;
output   m_axi_gmem_scale_BREADY;
input  [1:0] m_axi_gmem_scale_BRESP;
input  [C_M_AXI_GMEM_SCALE_ID_WIDTH - 1:0] m_axi_gmem_scale_BID;
input  [C_M_AXI_GMEM_SCALE_BUSER_WIDTH - 1:0] m_axi_gmem_scale_BUSER;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_AWADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_AWID;
output  [7:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [C_M_AXI_GMEM_OUT_AWUSER_WIDTH - 1:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_WDATA;
output  [C_M_AXI_GMEM_OUT_WSTRB_WIDTH - 1:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_WID;
output  [C_M_AXI_GMEM_OUT_WUSER_WIDTH - 1:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_ARADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_ARID;
output  [7:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [C_M_AXI_GMEM_OUT_ARUSER_WIDTH - 1:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_RID;
input  [C_M_AXI_GMEM_OUT_RUSER_WIDTH - 1:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_BID;
input  [C_M_AXI_GMEM_OUT_BUSER_WIDTH - 1:0] m_axi_gmem_out_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] X;
wire   [63:0] Wt;
wire   [63:0] wsc;
wire   [63:0] bias;
wire   [63:0] step_v;
wire   [63:0] lo_v;
wire   [63:0] Y;
wire   [31:0] H;
wire   [31:0] W;
wire   [31:0] oc;
wire   [31:0] ic;
wire   [31:0] kh;
wire   [31:0] kw;
wire   [31:0] sh;
wire   [31:0] sw;
wire   [31:0] ph;
wire   [31:0] pw;
wire   [31:0] groups;
wire   [31:0] act;
wire   [31:0] perch;
wire   [31:0] step;
wire   [31:0] lo;
reg   [31:0] lo_read_reg_2526;
reg   [31:0] step_read_reg_2531;
reg   [31:0] perch_read_reg_2536;
reg   [31:0] act_read_reg_2541;
reg   [31:0] groups_read_reg_2546;
reg   [31:0] pw_read_reg_2551;
reg   [31:0] ph_read_reg_2556;
reg   [31:0] sw_read_reg_2561;
reg   [31:0] sh_read_reg_2566;
reg   [31:0] kw_read_reg_2571;
reg   [31:0] kh_read_reg_2576;
reg   [31:0] ic_read_reg_2581;
reg   [31:0] oc_read_reg_2586;
reg   [31:0] W_read_reg_2591;
reg   [31:0] H_read_reg_2596;
reg   [63:0] Y_read_reg_2601;
reg   [63:0] lo_v_read_reg_2606;
reg   [63:0] step_v_read_reg_2611;
reg   [63:0] bias_read_reg_2616;
reg   [63:0] wsc_read_reg_2621;
reg   [63:0] Wt_read_reg_2626;
reg   [63:0] X_read_reg_2631;
wire    grp_y26_conv2d_hls_fu_1392_ap_start;
wire    grp_y26_conv2d_hls_fu_1392_ap_done;
wire    grp_y26_conv2d_hls_fu_1392_ap_idle;
wire    grp_y26_conv2d_hls_fu_1392_ap_ready;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WVALID;
wire   [127:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WDATA;
wire   [15:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WSTRB;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WLAST;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WID;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_RREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_BREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WDATA;
wire   [7:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WSTRB;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WLAST;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WID;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_RREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_BREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WVALID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WDATA;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WSTRB;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WLAST;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WID;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_RREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_BREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WVALID;
wire   [255:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WDATA;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WSTRB;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WLAST;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WID;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARVALID;
wire   [63:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARADDR;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARID;
wire   [31:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARLEN;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARSIZE;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARBURST;
wire   [1:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARLOCK;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARCACHE;
wire   [2:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARPROT;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARQOS;
wire   [3:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARREGION;
wire   [0:0] grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARUSER;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_RREADY;
wire    grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_BREADY;
wire    gmem_act_0_AWREADY;
wire    gmem_act_0_WREADY;
reg    gmem_act_0_ARVALID;
wire    gmem_act_0_ARREADY;
wire    gmem_act_0_RVALID;
reg    gmem_act_0_RREADY;
wire   [127:0] gmem_act_0_RDATA;
wire   [11:0] gmem_act_0_RFIFONUM;
wire    gmem_act_0_BVALID;
reg    gmem_out_0_AWVALID;
wire    gmem_out_0_AWREADY;
reg    gmem_out_0_WVALID;
wire    gmem_out_0_WREADY;
wire    gmem_out_0_ARREADY;
wire    gmem_out_0_RVALID;
wire   [255:0] gmem_out_0_RDATA;
wire   [8:0] gmem_out_0_RFIFONUM;
wire    gmem_out_0_BVALID;
reg    gmem_out_0_BREADY;
wire    gmem_scale_0_AWREADY;
wire    gmem_scale_0_WREADY;
reg    gmem_scale_0_ARVALID;
wire    gmem_scale_0_ARREADY;
wire    gmem_scale_0_RVALID;
reg    gmem_scale_0_RREADY;
wire   [31:0] gmem_scale_0_RDATA;
wire   [8:0] gmem_scale_0_RFIFONUM;
wire    gmem_scale_0_BVALID;
wire    gmem_wt_0_AWREADY;
wire    gmem_wt_0_WREADY;
reg    gmem_wt_0_ARVALID;
wire    gmem_wt_0_ARREADY;
wire    gmem_wt_0_RVALID;
reg    gmem_wt_0_RREADY;
wire   [63:0] gmem_wt_0_RDATA;
wire   [10:0] gmem_wt_0_RFIFONUM;
wire    gmem_wt_0_BVALID;
reg    grp_y26_conv2d_hls_fu_1392_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_y26_conv2d_hls_fu_1392_ap_start_reg = 1'b0;
end

y26_conv_top_y26_conv2d_hls grp_y26_conv2d_hls_fu_1392(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_y26_conv2d_hls_fu_1392_ap_start),
    .ap_done(grp_y26_conv2d_hls_fu_1392_ap_done),
    .ap_idle(grp_y26_conv2d_hls_fu_1392_ap_idle),
    .ap_ready(grp_y26_conv2d_hls_fu_1392_ap_ready),
    .m_axi_gmem_act_0_AWVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWVALID),
    .m_axi_gmem_act_0_AWREADY(1'b0),
    .m_axi_gmem_act_0_AWADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWADDR),
    .m_axi_gmem_act_0_AWID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWID),
    .m_axi_gmem_act_0_AWLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWLEN),
    .m_axi_gmem_act_0_AWSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWSIZE),
    .m_axi_gmem_act_0_AWBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWBURST),
    .m_axi_gmem_act_0_AWLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWLOCK),
    .m_axi_gmem_act_0_AWCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWCACHE),
    .m_axi_gmem_act_0_AWPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWPROT),
    .m_axi_gmem_act_0_AWQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWQOS),
    .m_axi_gmem_act_0_AWREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWREGION),
    .m_axi_gmem_act_0_AWUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_AWUSER),
    .m_axi_gmem_act_0_WVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WVALID),
    .m_axi_gmem_act_0_WREADY(1'b0),
    .m_axi_gmem_act_0_WDATA(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WDATA),
    .m_axi_gmem_act_0_WSTRB(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WSTRB),
    .m_axi_gmem_act_0_WLAST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WLAST),
    .m_axi_gmem_act_0_WID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WID),
    .m_axi_gmem_act_0_WUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_WUSER),
    .m_axi_gmem_act_0_ARVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARVALID),
    .m_axi_gmem_act_0_ARREADY(gmem_act_0_ARREADY),
    .m_axi_gmem_act_0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARADDR),
    .m_axi_gmem_act_0_ARID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARID),
    .m_axi_gmem_act_0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARLEN),
    .m_axi_gmem_act_0_ARSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARSIZE),
    .m_axi_gmem_act_0_ARBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARBURST),
    .m_axi_gmem_act_0_ARLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARLOCK),
    .m_axi_gmem_act_0_ARCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARCACHE),
    .m_axi_gmem_act_0_ARPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARPROT),
    .m_axi_gmem_act_0_ARQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARQOS),
    .m_axi_gmem_act_0_ARREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARREGION),
    .m_axi_gmem_act_0_ARUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARUSER),
    .m_axi_gmem_act_0_RVALID(gmem_act_0_RVALID),
    .m_axi_gmem_act_0_RREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_RREADY),
    .m_axi_gmem_act_0_RDATA(gmem_act_0_RDATA),
    .m_axi_gmem_act_0_RLAST(1'b0),
    .m_axi_gmem_act_0_RID(1'd0),
    .m_axi_gmem_act_0_RFIFONUM(gmem_act_0_RFIFONUM),
    .m_axi_gmem_act_0_RUSER(1'd0),
    .m_axi_gmem_act_0_RRESP(2'd0),
    .m_axi_gmem_act_0_BVALID(1'b0),
    .m_axi_gmem_act_0_BREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_BREADY),
    .m_axi_gmem_act_0_BRESP(2'd0),
    .m_axi_gmem_act_0_BID(1'd0),
    .m_axi_gmem_act_0_BUSER(1'd0),
    .X(X_read_reg_2631),
    .H(H_read_reg_2596),
    .W(W_read_reg_2591),
    .m_axi_gmem_wt_0_AWVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWVALID),
    .m_axi_gmem_wt_0_AWREADY(1'b0),
    .m_axi_gmem_wt_0_AWADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWADDR),
    .m_axi_gmem_wt_0_AWID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWID),
    .m_axi_gmem_wt_0_AWLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWLEN),
    .m_axi_gmem_wt_0_AWSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWSIZE),
    .m_axi_gmem_wt_0_AWBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWBURST),
    .m_axi_gmem_wt_0_AWLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWLOCK),
    .m_axi_gmem_wt_0_AWCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWCACHE),
    .m_axi_gmem_wt_0_AWPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWPROT),
    .m_axi_gmem_wt_0_AWQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWQOS),
    .m_axi_gmem_wt_0_AWREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWREGION),
    .m_axi_gmem_wt_0_AWUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_AWUSER),
    .m_axi_gmem_wt_0_WVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WVALID),
    .m_axi_gmem_wt_0_WREADY(1'b0),
    .m_axi_gmem_wt_0_WDATA(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WDATA),
    .m_axi_gmem_wt_0_WSTRB(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WSTRB),
    .m_axi_gmem_wt_0_WLAST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WLAST),
    .m_axi_gmem_wt_0_WID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WID),
    .m_axi_gmem_wt_0_WUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_WUSER),
    .m_axi_gmem_wt_0_ARVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARVALID),
    .m_axi_gmem_wt_0_ARREADY(gmem_wt_0_ARREADY),
    .m_axi_gmem_wt_0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARADDR),
    .m_axi_gmem_wt_0_ARID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARID),
    .m_axi_gmem_wt_0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARLEN),
    .m_axi_gmem_wt_0_ARSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARSIZE),
    .m_axi_gmem_wt_0_ARBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARBURST),
    .m_axi_gmem_wt_0_ARLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARLOCK),
    .m_axi_gmem_wt_0_ARCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARCACHE),
    .m_axi_gmem_wt_0_ARPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARPROT),
    .m_axi_gmem_wt_0_ARQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARQOS),
    .m_axi_gmem_wt_0_ARREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARREGION),
    .m_axi_gmem_wt_0_ARUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARUSER),
    .m_axi_gmem_wt_0_RVALID(gmem_wt_0_RVALID),
    .m_axi_gmem_wt_0_RREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_RREADY),
    .m_axi_gmem_wt_0_RDATA(gmem_wt_0_RDATA),
    .m_axi_gmem_wt_0_RLAST(1'b0),
    .m_axi_gmem_wt_0_RID(1'd0),
    .m_axi_gmem_wt_0_RFIFONUM(gmem_wt_0_RFIFONUM),
    .m_axi_gmem_wt_0_RUSER(1'd0),
    .m_axi_gmem_wt_0_RRESP(2'd0),
    .m_axi_gmem_wt_0_BVALID(1'b0),
    .m_axi_gmem_wt_0_BREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_BREADY),
    .m_axi_gmem_wt_0_BRESP(2'd0),
    .m_axi_gmem_wt_0_BID(1'd0),
    .m_axi_gmem_wt_0_BUSER(1'd0),
    .Wt(Wt_read_reg_2626),
    .c_oc_val(oc_read_reg_2586),
    .c_ic_val(ic_read_reg_2581),
    .c_kh_val(kh_read_reg_2576),
    .c_kw_val(kw_read_reg_2571),
    .c_sh_val(sh_read_reg_2566),
    .c_sw_val(sw_read_reg_2561),
    .c_ph_val(ph_read_reg_2556),
    .c_pw_val(pw_read_reg_2551),
    .c_groups_val(groups_read_reg_2546),
    .c_act_val(act_read_reg_2541),
    .c_perch_val(perch_read_reg_2536),
    .c_step_val(step_read_reg_2531),
    .c_lo_val(lo_read_reg_2526),
    .m_axi_gmem_scale_0_AWVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWVALID),
    .m_axi_gmem_scale_0_AWREADY(1'b0),
    .m_axi_gmem_scale_0_AWADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWADDR),
    .m_axi_gmem_scale_0_AWID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWID),
    .m_axi_gmem_scale_0_AWLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWLEN),
    .m_axi_gmem_scale_0_AWSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWSIZE),
    .m_axi_gmem_scale_0_AWBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWBURST),
    .m_axi_gmem_scale_0_AWLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWLOCK),
    .m_axi_gmem_scale_0_AWCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWCACHE),
    .m_axi_gmem_scale_0_AWPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWPROT),
    .m_axi_gmem_scale_0_AWQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWQOS),
    .m_axi_gmem_scale_0_AWREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWREGION),
    .m_axi_gmem_scale_0_AWUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_AWUSER),
    .m_axi_gmem_scale_0_WVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WVALID),
    .m_axi_gmem_scale_0_WREADY(1'b0),
    .m_axi_gmem_scale_0_WDATA(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WDATA),
    .m_axi_gmem_scale_0_WSTRB(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WSTRB),
    .m_axi_gmem_scale_0_WLAST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WLAST),
    .m_axi_gmem_scale_0_WID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WID),
    .m_axi_gmem_scale_0_WUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_WUSER),
    .m_axi_gmem_scale_0_ARVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARVALID),
    .m_axi_gmem_scale_0_ARREADY(gmem_scale_0_ARREADY),
    .m_axi_gmem_scale_0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARADDR),
    .m_axi_gmem_scale_0_ARID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARID),
    .m_axi_gmem_scale_0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARLEN),
    .m_axi_gmem_scale_0_ARSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARSIZE),
    .m_axi_gmem_scale_0_ARBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARBURST),
    .m_axi_gmem_scale_0_ARLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARLOCK),
    .m_axi_gmem_scale_0_ARCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARCACHE),
    .m_axi_gmem_scale_0_ARPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARPROT),
    .m_axi_gmem_scale_0_ARQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARQOS),
    .m_axi_gmem_scale_0_ARREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARREGION),
    .m_axi_gmem_scale_0_ARUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARUSER),
    .m_axi_gmem_scale_0_RVALID(gmem_scale_0_RVALID),
    .m_axi_gmem_scale_0_RREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_RREADY),
    .m_axi_gmem_scale_0_RDATA(gmem_scale_0_RDATA),
    .m_axi_gmem_scale_0_RLAST(1'b0),
    .m_axi_gmem_scale_0_RID(1'd0),
    .m_axi_gmem_scale_0_RFIFONUM(gmem_scale_0_RFIFONUM),
    .m_axi_gmem_scale_0_RUSER(1'd0),
    .m_axi_gmem_scale_0_RRESP(2'd0),
    .m_axi_gmem_scale_0_BVALID(1'b0),
    .m_axi_gmem_scale_0_BREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_BREADY),
    .m_axi_gmem_scale_0_BRESP(2'd0),
    .m_axi_gmem_scale_0_BID(1'd0),
    .m_axi_gmem_scale_0_BUSER(1'd0),
    .c_step_v(step_v_read_reg_2611),
    .c_lo_v(lo_v_read_reg_2606),
    .c_wsc(wsc_read_reg_2621),
    .c_bias(bias_read_reg_2616),
    .m_axi_gmem_out_0_AWVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWVALID),
    .m_axi_gmem_out_0_AWREADY(gmem_out_0_AWREADY),
    .m_axi_gmem_out_0_AWADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWADDR),
    .m_axi_gmem_out_0_AWID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWID),
    .m_axi_gmem_out_0_AWLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWLEN),
    .m_axi_gmem_out_0_AWSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWSIZE),
    .m_axi_gmem_out_0_AWBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWBURST),
    .m_axi_gmem_out_0_AWLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWLOCK),
    .m_axi_gmem_out_0_AWCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWCACHE),
    .m_axi_gmem_out_0_AWPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWPROT),
    .m_axi_gmem_out_0_AWQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWQOS),
    .m_axi_gmem_out_0_AWREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWREGION),
    .m_axi_gmem_out_0_AWUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWUSER),
    .m_axi_gmem_out_0_WVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WVALID),
    .m_axi_gmem_out_0_WREADY(gmem_out_0_WREADY),
    .m_axi_gmem_out_0_WDATA(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WDATA),
    .m_axi_gmem_out_0_WSTRB(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WSTRB),
    .m_axi_gmem_out_0_WLAST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WLAST),
    .m_axi_gmem_out_0_WID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WID),
    .m_axi_gmem_out_0_WUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WUSER),
    .m_axi_gmem_out_0_ARVALID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARVALID),
    .m_axi_gmem_out_0_ARREADY(1'b0),
    .m_axi_gmem_out_0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARADDR),
    .m_axi_gmem_out_0_ARID(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARID),
    .m_axi_gmem_out_0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARLEN),
    .m_axi_gmem_out_0_ARSIZE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARSIZE),
    .m_axi_gmem_out_0_ARBURST(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARBURST),
    .m_axi_gmem_out_0_ARLOCK(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARLOCK),
    .m_axi_gmem_out_0_ARCACHE(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARCACHE),
    .m_axi_gmem_out_0_ARPROT(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARPROT),
    .m_axi_gmem_out_0_ARQOS(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARQOS),
    .m_axi_gmem_out_0_ARREGION(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARREGION),
    .m_axi_gmem_out_0_ARUSER(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_ARUSER),
    .m_axi_gmem_out_0_RVALID(1'b0),
    .m_axi_gmem_out_0_RREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_RREADY),
    .m_axi_gmem_out_0_RDATA(256'd0),
    .m_axi_gmem_out_0_RLAST(1'b0),
    .m_axi_gmem_out_0_RID(1'd0),
    .m_axi_gmem_out_0_RFIFONUM(9'd0),
    .m_axi_gmem_out_0_RUSER(1'd0),
    .m_axi_gmem_out_0_RRESP(2'd0),
    .m_axi_gmem_out_0_BVALID(gmem_out_0_BVALID),
    .m_axi_gmem_out_0_BREADY(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_BREADY),
    .m_axi_gmem_out_0_BRESP(2'd0),
    .m_axi_gmem_out_0_BID(1'd0),
    .m_axi_gmem_out_0_BUSER(1'd0),
    .Y(Y_read_reg_2601)
);

y26_conv_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .X(X),
    .Wt(Wt),
    .wsc(wsc),
    .bias(bias),
    .step_v(step_v),
    .lo_v(lo_v),
    .Y(Y),
    .H(H),
    .W(W),
    .oc(oc),
    .ic(ic),
    .kh(kh),
    .kw(kw),
    .sh(sh),
    .sw(sw),
    .ph(ph),
    .pw(pw),
    .groups(groups),
    .act(act),
    .perch(perch),
    .step(step),
    .lo(lo),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

y26_conv_top_gmem_act_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 106 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ACT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ACT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_ACT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_ACT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ACT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_ACT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_ACT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_ACT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_ACT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_ACT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_ACT_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 128 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 12 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 128 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_act_m_axi_U(
    .AWVALID(m_axi_gmem_act_AWVALID),
    .AWREADY(m_axi_gmem_act_AWREADY),
    .AWADDR(m_axi_gmem_act_AWADDR),
    .AWID(m_axi_gmem_act_AWID),
    .AWLEN(m_axi_gmem_act_AWLEN),
    .AWSIZE(m_axi_gmem_act_AWSIZE),
    .AWBURST(m_axi_gmem_act_AWBURST),
    .AWLOCK(m_axi_gmem_act_AWLOCK),
    .AWCACHE(m_axi_gmem_act_AWCACHE),
    .AWPROT(m_axi_gmem_act_AWPROT),
    .AWQOS(m_axi_gmem_act_AWQOS),
    .AWREGION(m_axi_gmem_act_AWREGION),
    .AWUSER(m_axi_gmem_act_AWUSER),
    .WVALID(m_axi_gmem_act_WVALID),
    .WREADY(m_axi_gmem_act_WREADY),
    .WDATA(m_axi_gmem_act_WDATA),
    .WSTRB(m_axi_gmem_act_WSTRB),
    .WLAST(m_axi_gmem_act_WLAST),
    .WID(m_axi_gmem_act_WID),
    .WUSER(m_axi_gmem_act_WUSER),
    .ARVALID(m_axi_gmem_act_ARVALID),
    .ARREADY(m_axi_gmem_act_ARREADY),
    .ARADDR(m_axi_gmem_act_ARADDR),
    .ARID(m_axi_gmem_act_ARID),
    .ARLEN(m_axi_gmem_act_ARLEN),
    .ARSIZE(m_axi_gmem_act_ARSIZE),
    .ARBURST(m_axi_gmem_act_ARBURST),
    .ARLOCK(m_axi_gmem_act_ARLOCK),
    .ARCACHE(m_axi_gmem_act_ARCACHE),
    .ARPROT(m_axi_gmem_act_ARPROT),
    .ARQOS(m_axi_gmem_act_ARQOS),
    .ARREGION(m_axi_gmem_act_ARREGION),
    .ARUSER(m_axi_gmem_act_ARUSER),
    .RVALID(m_axi_gmem_act_RVALID),
    .RREADY(m_axi_gmem_act_RREADY),
    .RDATA(m_axi_gmem_act_RDATA),
    .RLAST(m_axi_gmem_act_RLAST),
    .RID(m_axi_gmem_act_RID),
    .RUSER(m_axi_gmem_act_RUSER),
    .RRESP(m_axi_gmem_act_RRESP),
    .BVALID(m_axi_gmem_act_BVALID),
    .BREADY(m_axi_gmem_act_BREADY),
    .BRESP(m_axi_gmem_act_BRESP),
    .BID(m_axi_gmem_act_BID),
    .BUSER(m_axi_gmem_act_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_act_0_ARVALID),
    .I_CH0_ARREADY(gmem_act_0_ARREADY),
    .I_CH0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARADDR),
    .I_CH0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARLEN),
    .I_CH0_RVALID(gmem_act_0_RVALID),
    .I_CH0_RREADY(gmem_act_0_RREADY),
    .I_CH0_RDATA(gmem_act_0_RDATA),
    .I_CH0_RFIFONUM(gmem_act_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_act_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_act_0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem_act_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

y26_conv_top_gmem_out_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 11 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_OUT_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_out_m_axi_U(
    .AWVALID(m_axi_gmem_out_AWVALID),
    .AWREADY(m_axi_gmem_out_AWREADY),
    .AWADDR(m_axi_gmem_out_AWADDR),
    .AWID(m_axi_gmem_out_AWID),
    .AWLEN(m_axi_gmem_out_AWLEN),
    .AWSIZE(m_axi_gmem_out_AWSIZE),
    .AWBURST(m_axi_gmem_out_AWBURST),
    .AWLOCK(m_axi_gmem_out_AWLOCK),
    .AWCACHE(m_axi_gmem_out_AWCACHE),
    .AWPROT(m_axi_gmem_out_AWPROT),
    .AWQOS(m_axi_gmem_out_AWQOS),
    .AWREGION(m_axi_gmem_out_AWREGION),
    .AWUSER(m_axi_gmem_out_AWUSER),
    .WVALID(m_axi_gmem_out_WVALID),
    .WREADY(m_axi_gmem_out_WREADY),
    .WDATA(m_axi_gmem_out_WDATA),
    .WSTRB(m_axi_gmem_out_WSTRB),
    .WLAST(m_axi_gmem_out_WLAST),
    .WID(m_axi_gmem_out_WID),
    .WUSER(m_axi_gmem_out_WUSER),
    .ARVALID(m_axi_gmem_out_ARVALID),
    .ARREADY(m_axi_gmem_out_ARREADY),
    .ARADDR(m_axi_gmem_out_ARADDR),
    .ARID(m_axi_gmem_out_ARID),
    .ARLEN(m_axi_gmem_out_ARLEN),
    .ARSIZE(m_axi_gmem_out_ARSIZE),
    .ARBURST(m_axi_gmem_out_ARBURST),
    .ARLOCK(m_axi_gmem_out_ARLOCK),
    .ARCACHE(m_axi_gmem_out_ARCACHE),
    .ARPROT(m_axi_gmem_out_ARPROT),
    .ARQOS(m_axi_gmem_out_ARQOS),
    .ARREGION(m_axi_gmem_out_ARREGION),
    .ARUSER(m_axi_gmem_out_ARUSER),
    .RVALID(m_axi_gmem_out_RVALID),
    .RREADY(m_axi_gmem_out_RREADY),
    .RDATA(m_axi_gmem_out_RDATA),
    .RLAST(m_axi_gmem_out_RLAST),
    .RID(m_axi_gmem_out_RID),
    .RUSER(m_axi_gmem_out_RUSER),
    .RRESP(m_axi_gmem_out_RRESP),
    .BVALID(m_axi_gmem_out_BVALID),
    .BREADY(m_axi_gmem_out_BREADY),
    .BRESP(m_axi_gmem_out_BRESP),
    .BID(m_axi_gmem_out_BID),
    .BUSER(m_axi_gmem_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_out_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_out_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_out_0_RDATA),
    .I_CH0_RFIFONUM(gmem_out_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_out_0_AWVALID),
    .I_CH0_AWREADY(gmem_out_0_AWREADY),
    .I_CH0_AWADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWADDR),
    .I_CH0_AWLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWLEN),
    .I_CH0_WVALID(gmem_out_0_WVALID),
    .I_CH0_WREADY(gmem_out_0_WREADY),
    .I_CH0_WDATA(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WDATA),
    .I_CH0_WSTRB(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WSTRB),
    .I_CH0_BVALID(gmem_out_0_BVALID),
    .I_CH0_BREADY(gmem_out_0_BREADY)
);

y26_conv_top_gmem_scale_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_SCALE_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_SCALE_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_SCALE_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_SCALE_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_SCALE_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_SCALE_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_SCALE_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_SCALE_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_SCALE_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_SCALE_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_SCALE_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_scale_m_axi_U(
    .AWVALID(m_axi_gmem_scale_AWVALID),
    .AWREADY(m_axi_gmem_scale_AWREADY),
    .AWADDR(m_axi_gmem_scale_AWADDR),
    .AWID(m_axi_gmem_scale_AWID),
    .AWLEN(m_axi_gmem_scale_AWLEN),
    .AWSIZE(m_axi_gmem_scale_AWSIZE),
    .AWBURST(m_axi_gmem_scale_AWBURST),
    .AWLOCK(m_axi_gmem_scale_AWLOCK),
    .AWCACHE(m_axi_gmem_scale_AWCACHE),
    .AWPROT(m_axi_gmem_scale_AWPROT),
    .AWQOS(m_axi_gmem_scale_AWQOS),
    .AWREGION(m_axi_gmem_scale_AWREGION),
    .AWUSER(m_axi_gmem_scale_AWUSER),
    .WVALID(m_axi_gmem_scale_WVALID),
    .WREADY(m_axi_gmem_scale_WREADY),
    .WDATA(m_axi_gmem_scale_WDATA),
    .WSTRB(m_axi_gmem_scale_WSTRB),
    .WLAST(m_axi_gmem_scale_WLAST),
    .WID(m_axi_gmem_scale_WID),
    .WUSER(m_axi_gmem_scale_WUSER),
    .ARVALID(m_axi_gmem_scale_ARVALID),
    .ARREADY(m_axi_gmem_scale_ARREADY),
    .ARADDR(m_axi_gmem_scale_ARADDR),
    .ARID(m_axi_gmem_scale_ARID),
    .ARLEN(m_axi_gmem_scale_ARLEN),
    .ARSIZE(m_axi_gmem_scale_ARSIZE),
    .ARBURST(m_axi_gmem_scale_ARBURST),
    .ARLOCK(m_axi_gmem_scale_ARLOCK),
    .ARCACHE(m_axi_gmem_scale_ARCACHE),
    .ARPROT(m_axi_gmem_scale_ARPROT),
    .ARQOS(m_axi_gmem_scale_ARQOS),
    .ARREGION(m_axi_gmem_scale_ARREGION),
    .ARUSER(m_axi_gmem_scale_ARUSER),
    .RVALID(m_axi_gmem_scale_RVALID),
    .RREADY(m_axi_gmem_scale_RREADY),
    .RDATA(m_axi_gmem_scale_RDATA),
    .RLAST(m_axi_gmem_scale_RLAST),
    .RID(m_axi_gmem_scale_RID),
    .RUSER(m_axi_gmem_scale_RUSER),
    .RRESP(m_axi_gmem_scale_RRESP),
    .BVALID(m_axi_gmem_scale_BVALID),
    .BREADY(m_axi_gmem_scale_BREADY),
    .BRESP(m_axi_gmem_scale_BRESP),
    .BID(m_axi_gmem_scale_BID),
    .BUSER(m_axi_gmem_scale_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_scale_0_ARVALID),
    .I_CH0_ARREADY(gmem_scale_0_ARREADY),
    .I_CH0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARADDR),
    .I_CH0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARLEN),
    .I_CH0_RVALID(gmem_scale_0_RVALID),
    .I_CH0_RREADY(gmem_scale_0_RREADY),
    .I_CH0_RDATA(gmem_scale_0_RDATA),
    .I_CH0_RFIFONUM(gmem_scale_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_scale_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_scale_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem_scale_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

y26_conv_top_gmem_wt_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 14 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_WT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_WT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_WT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_WT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_WT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_WT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_WT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_WT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_WT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_WT_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 64 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 64 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_wt_m_axi_U(
    .AWVALID(m_axi_gmem_wt_AWVALID),
    .AWREADY(m_axi_gmem_wt_AWREADY),
    .AWADDR(m_axi_gmem_wt_AWADDR),
    .AWID(m_axi_gmem_wt_AWID),
    .AWLEN(m_axi_gmem_wt_AWLEN),
    .AWSIZE(m_axi_gmem_wt_AWSIZE),
    .AWBURST(m_axi_gmem_wt_AWBURST),
    .AWLOCK(m_axi_gmem_wt_AWLOCK),
    .AWCACHE(m_axi_gmem_wt_AWCACHE),
    .AWPROT(m_axi_gmem_wt_AWPROT),
    .AWQOS(m_axi_gmem_wt_AWQOS),
    .AWREGION(m_axi_gmem_wt_AWREGION),
    .AWUSER(m_axi_gmem_wt_AWUSER),
    .WVALID(m_axi_gmem_wt_WVALID),
    .WREADY(m_axi_gmem_wt_WREADY),
    .WDATA(m_axi_gmem_wt_WDATA),
    .WSTRB(m_axi_gmem_wt_WSTRB),
    .WLAST(m_axi_gmem_wt_WLAST),
    .WID(m_axi_gmem_wt_WID),
    .WUSER(m_axi_gmem_wt_WUSER),
    .ARVALID(m_axi_gmem_wt_ARVALID),
    .ARREADY(m_axi_gmem_wt_ARREADY),
    .ARADDR(m_axi_gmem_wt_ARADDR),
    .ARID(m_axi_gmem_wt_ARID),
    .ARLEN(m_axi_gmem_wt_ARLEN),
    .ARSIZE(m_axi_gmem_wt_ARSIZE),
    .ARBURST(m_axi_gmem_wt_ARBURST),
    .ARLOCK(m_axi_gmem_wt_ARLOCK),
    .ARCACHE(m_axi_gmem_wt_ARCACHE),
    .ARPROT(m_axi_gmem_wt_ARPROT),
    .ARQOS(m_axi_gmem_wt_ARQOS),
    .ARREGION(m_axi_gmem_wt_ARREGION),
    .ARUSER(m_axi_gmem_wt_ARUSER),
    .RVALID(m_axi_gmem_wt_RVALID),
    .RREADY(m_axi_gmem_wt_RREADY),
    .RDATA(m_axi_gmem_wt_RDATA),
    .RLAST(m_axi_gmem_wt_RLAST),
    .RID(m_axi_gmem_wt_RID),
    .RUSER(m_axi_gmem_wt_RUSER),
    .RRESP(m_axi_gmem_wt_RRESP),
    .BVALID(m_axi_gmem_wt_BVALID),
    .BREADY(m_axi_gmem_wt_BREADY),
    .BRESP(m_axi_gmem_wt_BRESP),
    .BID(m_axi_gmem_wt_BID),
    .BUSER(m_axi_gmem_wt_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_wt_0_ARVALID),
    .I_CH0_ARREADY(gmem_wt_0_ARREADY),
    .I_CH0_ARADDR(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARADDR),
    .I_CH0_ARLEN(grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARLEN),
    .I_CH0_RVALID(gmem_wt_0_RVALID),
    .I_CH0_RREADY(gmem_wt_0_RREADY),
    .I_CH0_RDATA(gmem_wt_0_RDATA),
    .I_CH0_RFIFONUM(gmem_wt_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_wt_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_wt_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(gmem_wt_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_y26_conv2d_hls_fu_1392_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_y26_conv2d_hls_fu_1392_ap_start_reg <= 1'b1;
        end else if ((grp_y26_conv2d_hls_fu_1392_ap_ready == 1'b1)) begin
            grp_y26_conv2d_hls_fu_1392_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        H_read_reg_2596 <= H;
        W_read_reg_2591 <= W;
        Wt_read_reg_2626 <= Wt;
        X_read_reg_2631 <= X;
        Y_read_reg_2601 <= Y;
        act_read_reg_2541 <= act;
        bias_read_reg_2616 <= bias;
        groups_read_reg_2546 <= groups;
        ic_read_reg_2581 <= ic;
        kh_read_reg_2576 <= kh;
        kw_read_reg_2571 <= kw;
        lo_read_reg_2526 <= lo;
        lo_v_read_reg_2606 <= lo_v;
        oc_read_reg_2586 <= oc;
        perch_read_reg_2536 <= perch;
        ph_read_reg_2556 <= ph;
        pw_read_reg_2551 <= pw;
        sh_read_reg_2566 <= sh;
        step_read_reg_2531 <= step;
        step_v_read_reg_2611 <= step_v;
        sw_read_reg_2561 <= sw;
        wsc_read_reg_2621 <= wsc;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_y26_conv2d_hls_fu_1392_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_y26_conv2d_hls_fu_1392_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_y26_conv2d_hls_fu_1392_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_act_0_ARVALID = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_ARVALID;
    end else begin
        gmem_act_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_act_0_RREADY = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_act_0_RREADY;
    end else begin
        gmem_act_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_out_0_AWVALID = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_AWVALID;
    end else begin
        gmem_out_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_out_0_BREADY = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_BREADY;
    end else begin
        gmem_out_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_out_0_WVALID = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_out_0_WVALID;
    end else begin
        gmem_out_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_scale_0_ARVALID = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_ARVALID;
    end else begin
        gmem_scale_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_scale_0_RREADY = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_scale_0_RREADY;
    end else begin
        gmem_scale_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_wt_0_ARVALID = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_ARVALID;
    end else begin
        gmem_wt_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_wt_0_RREADY = grp_y26_conv2d_hls_fu_1392_m_axi_gmem_wt_0_RREADY;
    end else begin
        gmem_wt_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_y26_conv2d_hls_fu_1392_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_y26_conv2d_hls_fu_1392_ap_start = grp_y26_conv2d_hls_fu_1392_ap_start_reg;

endmodule //y26_conv_top
